name: getx_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  get_storage: ^2.0.2
  flutter_svg: ^0.22.0
  connectivity: 3.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  pedantic: ^1.11.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter.ttf
    - family: Fryo
      fonts: 
        - asset: assets/fonts/Fryo.ttf
  uses-material-design: true

